name: Scrape PDFs and generate sitemap daily

on:
  schedule:
    - cron: '0 2 * * *'  # Exécution quotidienne à 2h UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraping script
        run: python scrape_and_push.py

      - name: Generate sitemap
        run: python generate_sitemap.py

      - name: Vérifier les fichiers générés
        run: |
          echo "Contenu du répertoire après génération :"
          ls -lh
          echo "Aperçu du sitemap.xml :"
          head -n 20 sitemap.xml || true

      - name: Commit and push changes (if any)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git fetch origin main
          git checkout main

          git add pdf_links.json sitemap.xml
          if git diff --cached --quiet; then
            echo "Aucun changement à commit."
          else
            git commit -m "Mise à jour automatique des PDF et du sitemap"
            git pull origin main --rebase
            git push origin HEAD:main
          fi
